trigger:
  branches:
    include:
      - main  # Trigger on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based build agent

jobs:
- job: Build
  displayName: 'Build Project'
  steps:
    - task: Checkout@1
      displayName: 'Checkout Code'

    - task: NodeTool@0  # If you are working with Node.js (use appropriate tasks for your language)
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '16.x'

    - script: |
        npm install
        npm run build
      displayName: 'Run build script'
